import type { Producto } from "./types";

// Productos de muestra con fotos reales del rubro para visualizar el catalogo
// mientras no hay Supabase conectado. Se usan automaticamente solo cuando
// faltan las env vars de Supabase (ver obtenerProductos / listarProductos);
// en cuanto se configuren, esto deja de usarse solo.
function img(kw: string, lock: number) {
  return `https://loremflickr.com/600/750/${kw}?lock=${lock}`;
}

export const MOCK_PRODUCTOS: Producto[] = [
  {
    id: "mock-1",
    nombre: "Aros Argolla Finas",
    descripcion_corta: "Argollas livianas de uso diario, cierre a presión.",
    imagen_url: img("gold-earrings", 11),
    categoria: "Aritos",
    subcategoria: "Aritos",
    aroma: null,
    estado: "Disponible",
    precio: 8500,
    destacado: true,
    tonos: [
      { nombre: "Dorado", hex: "#d4af37" },
      { nombre: "Plateado", hex: "#c0c0c0" },
    ],
    orden_display: 0,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "mock-2",
    nombre: "Aros Perla Blanca",
    descripcion_corta: "Perla sintética clásica, ideal para looks formales.",
    imagen_url: img("pearl-earrings", 22),
    categoria: "Aritos",
    subcategoria: "Aritos",
    aroma: null,
    estado: "Disponible",
    precio: 6200,
    destacado: false,
    tonos: null,
    orden_display: 1,
    created_at: "2026-01-01T00:00:01Z",
  },
  {
    id: "mock-3",
    nombre: "Aros Colgantes Dorados",
    descripcion_corta: "Diseño colgante liviano, largo medio.",
    imagen_url: img("gold-jewelry", 33),
    categoria: "Aritos",
    subcategoria: "Aritos",
    aroma: null,
    estado: "Sin stock",
    precio: 7800,
    destacado: false,
    tonos: [{ nombre: "Dorado", hex: "#d4af37" }],
    orden_display: 2,
    created_at: "2026-01-01T00:00:02Z",
  },
  {
    id: "mock-4",
    nombre: "Pulsera Cadena Fina",
    descripcion_corta: "Cadena delicada ajustable, combina con cualquier outfit.",
    imagen_url: img("gold-bracelet", 44),
    categoria: "Pulseras",
    subcategoria: "Pulseras",
    aroma: null,
    estado: "Disponible",
    precio: 7500,
    destacado: true,
    tonos: [
      { nombre: "Dorado", hex: "#d4af37" },
      { nombre: "Plateado", hex: "#c0c0c0" },
    ],
    orden_display: 0,
    created_at: "2026-01-01T00:00:03Z",
  },
  {
    id: "mock-5",
    nombre: "Pulsera Dije Corazón",
    descripcion_corta: "Dije corazón con detalle de circonias.",
    imagen_url: img("silver-bracelet", 55),
    categoria: "Pulseras",
    subcategoria: "Pulseras",
    aroma: null,
    estado: "Sin stock",
    precio: 9200,
    destacado: false,
    tonos: null,
    orden_display: 1,
    created_at: "2026-01-01T00:00:04Z",
  },
  {
    id: "mock-6",
    nombre: "Pulsera Charms",
    descripcion_corta: "Base ajustable con charms intercambiables.",
    imagen_url: img("bracelet-jewelry", 66),
    categoria: "Pulseras",
    subcategoria: "Pulseras",
    aroma: null,
    estado: "Disponible",
    precio: 8900,
    destacado: false,
    tonos: [{ nombre: "Plateado", hex: "#c0c0c0" }],
    orden_display: 2,
    created_at: "2026-01-01T00:00:05Z",
  },
  {
    id: "mock-7",
    nombre: "Collar Choker",
    descripcion_corta: "Choker ajustable de acero quirúrgico, no se decolora.",
    imagen_url: img("choker-necklace", 77),
    categoria: "Collares",
    subcategoria: "Collares",
    aroma: null,
    estado: "Disponible",
    precio: 10500,
    destacado: true,
    tonos: null,
    orden_display: 0,
    created_at: "2026-01-01T00:00:06Z",
  },
  {
    id: "mock-8",
    nombre: "Collar Perlas Clásico",
    descripcion_corta: "Hilo de perlas sintéticas, largo 45cm.",
    imagen_url: img("pearl-necklace", 88),
    categoria: "Collares",
    subcategoria: "Collares",
    aroma: null,
    estado: "Sin stock",
    precio: 12800,
    destacado: false,
    tonos: null,
    orden_display: 1,
    created_at: "2026-01-01T00:00:07Z",
  },
  {
    id: "mock-9",
    nombre: "Collar Cadena Dorada",
    descripcion_corta: "Cadena fina con dije geométrico minimalista.",
    imagen_url: img("gold-necklace", 99),
    categoria: "Collares",
    subcategoria: "Collares",
    aroma: null,
    estado: "Disponible",
    precio: 9800,
    destacado: false,
    tonos: [{ nombre: "Dorado", hex: "#d4af37" }],
    orden_display: 2,
    created_at: "2026-01-01T00:00:08Z",
  },
  {
    id: "mock-10",
    nombre: "Anillo Solitario Circonia",
    descripcion_corta: "Circonia central engarzada, banda fina.",
    imagen_url: img("diamond-ring", 100),
    categoria: "Anillos",
    subcategoria: "Anillos",
    aroma: null,
    estado: "Disponible",
    precio: 6800,
    destacado: false,
    tonos: [
      { nombre: "Dorado", hex: "#d4af37" },
      { nombre: "Plateado", hex: "#c0c0c0" },
    ],
    orden_display: 0,
    created_at: "2026-01-01T00:00:09Z",
  },
  {
    id: "mock-11",
    nombre: "Set Anillos Ajustables x3",
    descripcion_corta: "Combo de 3 anillos ajustables, apilables entre sí.",
    imagen_url: img("gold-ring", 111),
    categoria: "Anillos",
    subcategoria: "Anillos",
    aroma: null,
    estado: "Disponible",
    precio: 5400,
    destacado: true,
    tonos: null,
    orden_display: 1,
    created_at: "2026-01-01T00:00:10Z",
  },
  {
    id: "mock-12",
    nombre: "Anillo Banda Ancha",
    descripcion_corta: "Banda ancha lisa, terminación mate.",
    imagen_url: img("silver-ring", 122),
    categoria: "Anillos",
    subcategoria: "Anillos",
    aroma: null,
    estado: "Sin stock",
    precio: 7200,
    destacado: false,
    tonos: [{ nombre: "Plateado", hex: "#c0c0c0" }],
    orden_display: 2,
    created_at: "2026-01-01T00:00:11Z",
  },
  {
    id: "mock-13",
    nombre: "Spray Textil Lavanda",
    descripcion_corta: "Perfuma telas y ambientes, aroma relajante.",
    imagen_url: img("fabric-spray", 133),
    categoria: "Spray Textil",
    subcategoria: "Spray Textil",
    aroma: ["Lavanda"],
    estado: "Disponible",
    precio: 6500,
    destacado: true,
    tonos: null,
    orden_display: 0,
    created_at: "2026-01-01T00:00:12Z",
  },
  {
    id: "mock-14",
    nombre: "Difusor de Varillas Vainilla",
    descripcion_corta: "Difusor de ambiente 120ml, dura hasta 2 meses.",
    imagen_url: img("reed-diffuser", 144),
    categoria: "Difusor",
    subcategoria: "Difusor",
    aroma: ["Vainilla"],
    estado: "Disponible",
    precio: 11500,
    destacado: false,
    tonos: null,
    orden_display: 0,
    created_at: "2026-01-01T00:00:13Z",
  },
  {
    id: "mock-15",
    nombre: "Crema Hidratante Corporal",
    descripcion_corta: "Hidratación profunda, absorción rápida.",
    imagen_url: img("body-cream", 155),
    categoria: "Cremas",
    subcategoria: "Cremas",
    aroma: ["Coco"],
    estado: "Disponible",
    precio: 8200,
    destacado: false,
    tonos: null,
    orden_display: 0,
    created_at: "2026-01-01T00:00:14Z",
  },
  {
    id: "mock-16",
    nombre: "Vela Aromática Sándalo",
    descripcion_corta: "Vela de soja, 40hs de duración aproximada.",
    imagen_url: img("scented-candle", 166),
    categoria: "Vela Aromática",
    subcategoria: "Vela Aromática",
    aroma: ["Sándalo"],
    estado: "Disponible",
    precio: 9800,
    destacado: true,
    tonos: null,
    orden_display: 1,
    created_at: "2026-01-01T00:00:15Z",
  },
  {
    id: "mock-17",
    nombre: "Bufanda Tejida",
    descripcion_corta: "Bufanda de punto grueso, abrigo para días fríos.",
    imagen_url: img("knit-scarf", 177),
    categoria: "Invierno",
    subcategoria: "Invierno",
    aroma: null,
    estado: "Disponible",
    precio: 12500,
    destacado: false,
    tonos: null,
    orden_display: 0,
    created_at: "2026-01-01T00:00:16Z",
  },
  {
    id: "mock-18",
    nombre: "Guantes de Lana",
    descripcion_corta: "Guantes térmicos, talle único.",
    imagen_url: img("winter-gloves", 188),
    categoria: "Invierno",
    subcategoria: "Invierno",
    aroma: null,
    estado: "Sin stock",
    precio: 7400,
    destacado: false,
    tonos: null,
    orden_display: 1,
    created_at: "2026-01-01T00:00:17Z",
  },
];
